import { type Language } from '../types';

export const UI_TEXTS: Record<Language, Record<string, string>> = {
  es: {
    title: "Cabo Health Nova",
    subtitle: "Next-Gen Clinical AI | by Ivan Guaderrama",
    idle: "En espera",
    connecting: "Conectando...",
    listening: "Escuchando...",
    processing: "Sintetizando resumen...",
    completed: "Sesión completada",
    error: "Error",
    errorMicPermission: "Acceso al micrófono denegado. Por favor, habilite el acceso en la configuración de su navegador y recargue la página.",
    errorMicNotFound: "No se encontró un micrófono. Por favor, conecte uno y vuelva a intentarlo.",
    errorMicGeneric: "No se pudo acceder al micrófono. Por favor, verifique los permisos y el hardware. Use el botón de diagnóstico para resolver el problema.",
    microphoneDiagnostic: "Diagnóstico del Micrófono",
    errorConnection: "Hubo un error en la conexión. Por favor, verifique su conexión a internet y vuelva a intentarlo.",
    errorSummary: "No se pudo generar el resumen. Esto puede deberse a un problema de conexión o a que la conversación fue muy breve. Por favor, intente de nuevo.",
    errorApiKey: "La clave API de Gemini no está configurada. Por favor, asegúrese de que la variable de entorno esté configurada correctamente.",
    errorHttpsRequired: "El acceso al micrófono requiere una conexión segura (HTTPS). Por favor, asegúrese de que está en un sitio seguro.",
    startSession: "Iniciar Sesión",
    endSession: "Finalizar Sesión",
    processingButton: "Procesando...",
    spanish: "Español",
    english: "Inglés",
    transcriptPlaceholder: "La transcripción aparecerá aquí...",
    summaryPlaceholder: "El resumen clínico aparecerá aquí después de la sesión.",
    summaryProcessingTitle: "Modo de Síntesis Avanzada",
    summaryProcessingBody: "Procesando transcripción completa...",
    summaryReadyTitle: "Resumen Listo",
    summaryReadyBody: "El resumen clínico está listo para ser enviado al médico.",
    summaryError: "<h3>Transcripción demasiado corta</h3><p>No se pudo generar un resumen porque la conversación fue demasiado breve.</p>",
    you: "Tú",
    you_char: "T",
    copyToClipboardButton: "Copiar al Portapapeles",
    closeButton: "Cerrar",
    enterFullName: "Por favor, ingrese su nombre completo para comenzar",
    fullNameLabel: "Nombre Completo",
    dobLabel: "Fecha de Nacimiento",
    patientEmailLabel: "Su Correo Electrónico",
    doctorEmailLabel: "Correo del Médico",
    sendToDoctorButton: "Enviar al Médico",
    sendSummaryButton: "Enviar Resumen",
    sendingButton: "Enviando...",
    sentSuccessTitle: "Resumen Enviado",
    sentSuccessBody: "El resumen clínico ha sido enviado exitosamente a {doctorEmail}.",
    confirmationId: "ID de Confirmación:",
    doneButton: "Hecho",
    formError: "Por favor, complete todos los campos requeridos.",
    modalTitleSend: "Enviar Resumen Clínico al Médico",
    // Mode selection texts
    modeSelectionTitle: "Elige cómo prefieres comunicarte con Nova",
    modeVoiceTitle: "Hablar con Nova",
    modeVoiceDesc: "Conversación de voz",
    modeTextTitle: "Escribir a Nova",
    modeTextDesc: "Chat con dictado",
    // Text chat panel texts
    chatPlaceholder: "Escribe tu mensaje...",
    sendButton: "Enviar",
    dictateButton: "Dictar",
    stopDictation: "Detener",
    listeningDictation: "Escuchando...",
    novaTyping: "Nova está escribiendo...",
    switchToVoice: "Cambiar a voz",
    listenResponse: "Escuchar respuesta",
    dictationNotSupported: "Tu navegador no soporta dictado por voz",
    dictationError: "Error en dictado. Intenta de nuevo.",
  },
  en: {
    title: "Cabo Health Nova",
    subtitle: "Next-Gen Clinical AI | by Ivan Guaderrama",
    idle: "Idle",
    connecting: "Connecting...",
    listening: "Listening...",
    processing: "Synthesizing summary...",
    completed: "Session completed",
    error: "Error",
    errorMicPermission: "Microphone access denied. Please enable access in your browser settings and reload the page.",
    errorMicNotFound: "No microphone found. Please connect one and try again.",
    errorMicGeneric: "Could not access the microphone. Please check permissions and hardware. Use the diagnostic button to resolve the issue.",
    microphoneDiagnostic: "Microphone Diagnostic",
    errorConnection: "A connection error occurred. Please check your internet connection and try again.",
    errorSummary: "Failed to generate summary. This might be due to a connection issue or a very short conversation. Please try again.",
    errorApiKey: "Gemini API key is not configured. Please ensure the environment variable is set correctly.",
    errorHttpsRequired: "Microphone access requires a secure connection (HTTPS). Please ensure you are on a secure site.",
    startSession: "Start Session",
    endSession: "End Session",
    processingButton: "Processing...",
    spanish: "Spanish",
    english: "English",
    transcriptPlaceholder: "The transcript will appear here...",
    summaryPlaceholder: "The clinical summary will appear here after the session.",
    summaryProcessingTitle: "Advanced Synthesis Mode",
    summaryProcessingBody: "Processing full transcript...",
    summaryReadyTitle: "Summary Ready",
    summaryReadyBody: "The clinical summary is ready to be sent to the doctor.",
    summaryError: "<h3>Transcript too short</h3><p>Could not generate a summary because the conversation was too brief.</p>",
    you: "You",
    you_char: "Y",
    copyToClipboardButton: "Copy to Clipboard",
    closeButton: "Close",
    enterFullName: "Please enter your full name to begin",
    fullNameLabel: "Full Name",
    dobLabel: "Date of Birth",
    patientEmailLabel: "Your Email",
    doctorEmailLabel: "Doctor's Email",
    sendToDoctorButton: "Send to Doctor",
    sendSummaryButton: "Send Summary",
    sendingButton: "Sending...",
    sentSuccessTitle: "Summary Sent",
    sentSuccessBody: "The clinical summary has been successfully sent to {doctorEmail}.",
    confirmationId: "Confirmation ID:",
    doneButton: "Done",
    formError: "Please fill out all required fields.",
    modalTitleSend: "Send Clinical Summary to Doctor",
    // Mode selection texts
    modeSelectionTitle: "Choose how you prefer to communicate with Nova",
    modeVoiceTitle: "Talk to Nova",
    modeVoiceDesc: "Voice conversation",
    modeTextTitle: "Write to Nova",
    modeTextDesc: "Chat with dictation",
    // Text chat panel texts
    chatPlaceholder: "Type your message...",
    sendButton: "Send",
    dictateButton: "Dictate",
    stopDictation: "Stop",
    listeningDictation: "Listening...",
    novaTyping: "Nova is typing...",
    switchToVoice: "Switch to voice",
    listenResponse: "Listen to response",
    dictationNotSupported: "Your browser does not support voice dictation",
    dictationError: "Dictation error. Try again.",
  },
};
